### ISSUE TITLE
Specify named graphs based on categories (col D in spreadsheet)

### ISSUE THREAD

**Issue by recalcitrantsupplant** [Kurrawong/fair-ease-matcher#10]
https://docs.google.com/spreadsheets/d/17-MXAugIzrxBICMkh1VYvqkPfiwgLrOP8WXHnRaAV8s/edit#gid=0

e.g. VALUES ?graph {<http://qudt.org/2.1/vocab/unit> <http://P06> }

**Comment by gwemon** [comment]
@recalcitrantsupplant  I have added a tab to our shared spreadsheet called: "categorisation of Vocabs" I have ignored the entries that could probably be removed from the KB and only kept the ones that refer to either parameters, instruments, platforms or a combination of 2 or 3 of these. This means that something labelled as a "keyword" will fall in the instrument category if the match is on a vocabulary known to contain instrument information.
@alko-k  FYI

**Comment by recalcitrantsupplant** [comment]
named graphs are now in use as per https://github.com/Kurrawong/fair-ease-matcher/commit/26e6fb80e47e853095df21c0b638cdec1bd6b1a2
