### ISSUE TITLE
Improve fuzzy match by bringing the most relevant results at top

### ISSUE THREAD

**Issue by gwemon** [Kurrawong/fair-ease-matcher#29]
A good example of this is the Wildcard match for Variable terms from ICOS Data Portal 
e.g. - (2020) from NO-SOOP-Nuka Arctica, 2017-07-06–2017-

The Search terms are multi terms that should all have matches in the KB but the current search is bringing at the top matches that are not very relevant while the other more relevant ones are not displayed.

**Comment by gwemon** [comment]
Choosing most relevant result requires knowledge on context (obtained from the KB) - i.e. if the term to match was tagged as an instrument then instrument collections would come on top.

**Comment by recalcitrantsupplant** [comment]
Results are ordered by weight, and the themes from graphs are now shown.
