### ISSUE TITLE
Do not use the skos:definition for the fuzzy or wilcard matches

### ISSUE THREAD

**Issue by gwemon** [Kurrawong/fair-ease-matcher#37]
using skos:definition brings up too many false matches and the probability of finding something through the definition that has not already been found through the other fields is remote and probably not the best approach.
@alko-k  FYI

**Comment by recalcitrantsupplant** [comment]
Fixed in commit [25d8cde7d252f817682f0c4bfbaf1f75fbdf712e](https://github.com/Kurrawong/fair-ease-matcher/commit/25d8cde7d252f817682f0c4bfbaf1f75fbdf712e)
