### ISSUE TITLE
Vocabs not tagged as a "Platform" vocab appears under "Platform"

### ISSUE THREAD

**Issue by gwemon** [Kurrawong/fair-ease-matcher#39]
See screenshot where under the "Platform" Wildcard tab we have 2 vocabs with a match: One is a platform vocab but the other was not tagged as belonging to the platform graph so I was not expecting to see it there. Is it because this has not yet fully implemented?

![Image](https://github.com/Kurrawong/fair-ease-matcher/assets/32506510/6751fac4-454b-4f54-875f-8a7fa514882d)

**Comment by recalcitrantsupplant** [comment]
Do you recall which record this was for?

**Comment by gwemon** [comment]
Same as the other: ICOS Data Portal (2020) from NO-SOOP-Nuka Arctica, 2017-07-06–2017-
