### ISSUE TITLE
Some terms reported as not found when they should be found in the KB either as wildcard or proximity matches

### ISSUE THREAD

**Issue by gwemon** [Kurrawong/fair-ease-matcher#60]
Selected source: VITO /Copernicus Global Land Services
Selected dataset: 2nd dataset
Lake Water Quality 2016-2018 (raster 1 km), global, 10-daily - version 1
Bug: It reported the following in bold as not found which are either wildcard or proximity matches
<gco:CharacterString>water</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>>**algal bloom**</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>>**aquatic environment**</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>>**freshwater**</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>freshwater quality</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>>**inland water**</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>>**lagoon**</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>lake</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>dam</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>phytoplankton</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>turbidity</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>water monitoring</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>water quality</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>water reservoir</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>climate</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>seasonal variation</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>environmental data</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>environmental monitoring</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>monitoring</gco:CharacterString>
</gmd:keyword>
<gmd:keyword>
<gco:CharacterString>remote sensing</gco:CharacterString>
</gmd:keyword>

**Comment by recalcitrantsupplant** [comment]
Addressed in https://github.com/Kurrawong/fair-ease-matcher/commit/308999172b661c8e9b843d4588113f659b82c694

**Comment by gwemon** [comment]
Thank you - these terms are now listed as found.
