### ISSUE TITLE
URI are not removed from "Terms not found" even though they are listed in the URI match

### ISSUE THREAD

**Issue by gwemon** [Kurrawong/fair-ease-matcher#61]
This can be seen in these datasets:
1) Selected data source: CMEMS
Selected dataset: Global Ocean- Real time in-situ observations objective analysis
Link to the XML: https://gs-service-production.geodab.eu/gs-service/services/essi/csw?service=CSW&version=2.0.2&request=GetRecordById&id=9a5a0566-48d1-4d9b-9261-7d972bbc5839&outputschema=http://www.isotc211.org/2005/gmi&elementSetName=full
Bug: P07 URI listed in Terms not found even though they are listed in the URI match

2) EMODnet chemistry
Selected dataset: Combined DIVA 4D 10-year analysis of Water body ammonium
Link to XML: https://gs-service-production.geodab.eu/gs-service/services/essi/csw?service=CSW&version=2.0.2&request=GetRecordById&id=e61d12cd-837f-49ff-a0e1-3a694ab84bc5&outputschema=http://www.isotc211.org/2005/gmi&elementSetName=full

**Comment by recalcitrantsupplant** [comment]
addressed in [commit](https://github.com/Kurrawong/fair-ease-matcher/commit/9ed3862b8832c9ac8194496259014c9853baac79)

**Comment by gwemon** [comment]
For the EMODnet chem dataset mentioned above in this ticket, the URIs are still listed in the "not found" section even though they do appear in the URI match results. see e.g. https://vocab.nerc.ac.uk/collection/P36/current/FERTIL/ screenshot of test carried out 03/03/2024.
![image](https://github.com/Kurrawong/fair-ease-matcher/assets/32506510/40000b77-0807-40a8-9500-945cd0f90275)
