### ISSUE TITLE
SDN:P02::ALKY found as exact match but preflabel only found as proximity match (all the other P02 were found as exact matches for both label and ID)

### ISSUE THREAD

**Issue by gwemon** [Kurrawong/fair-ease-matcher#63]
Selected source: SeaDataNet open datasets
Selected Dataset: SeaDataNet - Biological oceanography from German Oceanographic Datacentre (PointOfContact; Data Distributor), State Office for Agriculture, Environment and Rural Areas of Schleswig Holstein (Data Custodian), point observations
Link to XML: https://gs-service-production.geodab.eu/gs-service/services/essi/csw?service=CSW&version=2.0.2&request=GetRecordById&id=sdn-open:urn:SDN:CDI:LOCAL:96-2537-96-ds01-4&outputschema=http://www.isotc211.org/2005/gmi&elementSetName=full
Bug: SDN:P02::ALKY found as exact match but preflabel only found as proximity match (all the other P02 were found as exact matches for both label and ID)

**Comment by recalcitrantsupplant** [comment]
These results appear as URI matches, with the changes in https://github.com/Kurrawong/fair-ease-matcher/commit/9ed3862b8832c9ac8194496259014c9853baac79 to address #61 , the Exact/Proximity matches will no longer show **as there is already a match for the URI the preflabel is linked to (as a URI Match)**.

The likely cause of the matches not appearing would be the same problem noted in #62 (and the possible solutions would be the same).
